name: Nativelink
description:
  Action to use https://app.nativelink.com/ in a GitHub Actions workflow
author: Trace Machina <tom@tracemachina.com>

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: share-2
  color: purple

# Define your inputs here.
inputs:
  api_key:
    description: API Key for Nativelink
    required: true
  account:
    description: Nativelink Account Name
    required: true
  prefix:
    description: Nativelink Cache Prefix
    required: true
  cache_url:
    description: Nativelink Cache URL
  bes_url:
    description: Nativelink Build Event Service URL
  bes_results_url:
    description: Nativelink Build Results URL
  scheduler_url:
    description: Nativelink Scheduler URL
  remote_timeout:
    description: Remote Execution Timeout in seconds
    default: 600
  environment:
    description: Nativelink Environment
    default: prod

runs:
  using: node24
  main: dist/index.js
