name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-typescript:
    name: TypeScript Tests
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v5

      - name: Prepare Worker
        uses: ./.github/actions/prepare-nix

      - name: Install Dependencies
        id: pnpm-install
        run:
          nix develop --impure --command bash -c "pnpm install
          --frozen-lockfile"

      - name: Test
        id: npm-ci-test
        run: nix develop --impure --command bash -c "pnpm ci-test"

  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v5

      - name: Test Local Action
        id: test-action
        uses: ./
        with:
          api_key: demo-key
          account: tom-parker-shemilt
          prefix: tom-parker-shemilt-y0738m
          cache_url: grpcs://cas-tom-parker-shemilt-y0738m.build-faster.nativelink.net
          bes_url: grpcs://bes-tom-parker-shemilt-y0738m
          bes_results_url: https://app.nativelink.com/a/tom-parker-shemilt/build
          scheduler_url: grpcs://scheduler-tom-parker-shemilt-y0738m.build-faster.nativelink.net:443
          remote_timeout: 600
          environment: prod
