# This workflow checks the statuses of cached dependencies used in this action
# with the help of the Licensed tool. If any licenses are invalid or missing,
# this workflow will fail. See: https://github.com/licensee/licensed

name: Licensed

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  licensed:
    name: Check Licenses
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v5

      - name: Prepare Worker
        uses: ./.github/actions/prepare-nix

      - name: Install Dependencies
        id: pnpm-ci
        run: nix develop --impure --command bash -c "pnpm ci"

      # If this is a workflow_dispatch event, update the cached licenses.
      - if: ${{ github.event_name == 'workflow_dispatch' }}
        name: Update Licenses
        id: update-licenses
        run: nix develop --impure --command bash -c "licensed cache"

      # Then, commit the updated licenses to the repository.
      - if: ${{ github.event_name == 'workflow_dispatch' }}
        name: Commit Licenses
        id: commit-licenses
        run: |
          git config --local user.email "licensed-ci@users.noreply.github.com"
          git config --local user.name "licensed-ci"
          git add .
          git commit -m "Auto-update license files"
          git push

      # Last, check the status of the cached licenses.
      - name: Check Licenses
        id: check-licenses
        run: nix develop --impure --command bash -c "licensed status"
